import styles from "./index.module.css";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import Link from "next/link";

export default function Home() {
  const { data: sessionData } = useSession();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>Ai Pages Example</h1>
          <div className={styles.cardRow}>
            <div className={styles.card}>
              <h3 className={styles.cardTitle}>
                Login status:{" "}
                {sessionData ? (
                  <span>{sessionData.user?.name}</span>
                ) : (
                  "Logged Out"
                )}
              </h3>
              <div className={styles.cardText}>
                <button
                  onClick={
                    sessionData ? () => void signOut() : () => void signIn()
                  }
                >
                  {sessionData ? "Sign out" : "Sign in"}
                </button>
              </div>
            </div>
            <Link className={styles.card} href="chat">
              <h3 className={styles.cardTitle}>Go to Chat →</h3>
              <div className={styles.cardText}>
                <p>Chat with Vercel Ai</p>
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
